### ISSUE TITLE
[Bug]: Helm chart fails to deploy due to invalid requests/limits

### ISSUE THREAD

**Issue by dagan** [raft-tech/konfirm#182]
### What went wrong?

Resources are currently defaulted to:
```yaml
resources:
  requests:
    cpu: 0.25
    memory: 128MiB
  limits:
    cpu: 0.25
    memory: 128MiB
```

But should be:
```yaml
resources:
  requests:
    cpu: "0.25"
    memory: 128Mi
  limits:
    cpu: "0.25"
    memory: 128Mi
```

### Version

v0.2.0 (Latest)

### What version of Kubernetes are you using?

v1.30

### Which Kubernetes distribution are you using?

N/A

### Code of Conduct

- [X] I agree to follow the Konfirm Code of Conduct
