### ISSUE TITLE
Dependabot should run daily instead of weekly

### ISSUE THREAD

**Issue by dagan** [raft-tech/konfirm#186]
### What went wrong?

Currently, Dependabot is scheduled to run weekly (which means on Mondays). Instead, it should run daily.

```yaml
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```

### Version

v0.2.0 (Latest)

### Code of Conduct

- [X] I agree to follow the Konfirm Code of Conduct
